### ISSUE TITLE
Menu sub items don't appear

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#147] opened 2018-05-22 12:01 UTC
**Current Behavior**: Menu subitems  are specified in appearance/menus but do not appear on the site.

**Desired Behavior**: Menu subitems should appear.

**Other details:** Example on the staging site – Take a look at the Research menu. This is also the case on the Production site with a different Research menu. Related issue: the Interviews menu item on the Staging site comes up blank  – this is not the case on the production site

**Comment by ethanbutler** [comment] 2018-05-27 18:04
Duplicate of #137

**Closed by ethanbutler** 2018-05-27 18:04 UTC
Labels: bug
